// Promotion — turns approved drafts into the bundled content model.
//
// Generates src/data/countryContent.js from content-sources/drafts/. Only
// countries with real prose are promoted; a hollow draft (cy, ps — no Factbook
// entry to draft from) is skipped rather than published empty.
//
// This file is GENERATED. Edit a draft and re-run; never hand-edit the output.
// Hand-authored overrides live in COUNTRY_PAGES in countryPages.js and win over
// anything here.
//
// Run:  npm run content:promote
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const DRAFT_DIR = "content-sources/drafts";
const OUT = "src/data/countryContent.js";

// Draft prose field -> the fact key the app and the chunker use. `hook` is not
// here: it becomes the page summary, which is the "why should I care?" lead.
const FACT_KEYS = {
  physicalGeography: "physical_geography",
  climate: "climate",
  economy: "economy",
  peopleAndCulture: "people_and_culture",
};

async function main() {
  const files = (await readdir(DRAFT_DIR)).filter((f) => f.endsWith(".json")).sort();
  const entries = [];
  const skipped = [];

  for (const file of files) {
    const d = JSON.parse(await readFile(path.join(DRAFT_DIR, file), "utf8"));
    const s = d.structured;
    const prose = d.prose ?? {};
    const hasProse = Object.values(prose).some((v) => (v ?? "").trim());
    if (!hasProse) { skipped.push(d.iso); continue; }

    const facts = {};
    for (const [from, key] of Object.entries(FACT_KEYS)) {
      const text = (prose[from] ?? "").trim();
      if (text) facts[key] = text;
    }
    // Provenance travels with the content, for citation and licence
    // cleanliness. Underscore-prefixed so it is metadata rather than a fact:
    // the chunker skips those keys, and the page's FACT_ORDER allowlist never
    // renders it.
    if (Object.keys(facts).length) {
      facts._sources = {
        prose: "CIA World Factbook (public domain)",
        structured: "Wikidata (CC0)",
      };
    }

    entries.push({
      code: d.iso,
      summary: (prose.hook ?? "").trim() || null,
      population: s.population ?? null,
      areaKm2: s.areaKm2 ?? null,
      // NOTE: deliberately no `region`. Wikidata's continent taxonomy disagrees
      // with ours ("North America" vs "Americas", "Insular Oceania", and
      // Georgia/Kazakhstan/Turkey in Europe), and `region` drives region filters
      // and learning paths. getCountryPage() keeps taking region from
      // countries.js. See ADR 0001.
      neighbors: s.landBorderCodes ?? [],
      facts,
    });
  }

  const body = entries
    .map((e) => {
      const facts = Object.entries(e.facts)
        .map(([k, v]) =>
          k === "_sources"
            ? `      _sources: ${JSON.stringify(v)},`
            : `      ${k}: ${JSON.stringify(v)},`
        )
        .join("\n");
      return [
        `  ${e.code}: {`,
        `    summary: ${JSON.stringify(e.summary)},`,
        `    population: ${e.population},`,
        `    areaKm2: ${e.areaKm2},`,
        `    neighbors: ${JSON.stringify(e.neighbors)},`,
        `    facts: {`,
        facts,
        `    },`,
        `  },`,
      ].join("\n");
    })
    .join("\n");

  const header = `// GENERATED by scripts/promote-drafts.js — do not edit by hand.
//
// Country content promoted from content-sources/drafts/, which are reviewed as
// a git diff before promotion. Prose is drafted by Claude from CIA World
// Factbook text (public domain); structured values come from Wikidata (CC0).
// See docs/adr/0001-content-enrichment-sourcing.md.
//
// This is both the seed source for content.countries and the offline baseline
// the app falls back to, so Postgres holds exactly what renders offline.
//
// ${entries.length} countries. ${skipped.length ? `Not promoted (no source prose): ${skipped.join(", ")}.` : ""}
export const COUNTRY_CONTENT = {
`;

  await writeFile(OUT, header + body + "\n};\n");
  const bytes = (await readFile(OUT)).length;
  console.log(`Wrote ${OUT}: ${entries.length} countries, ${(bytes / 1024).toFixed(0)} KB`);
  if (skipped.length) console.log(`Skipped (no prose): ${skipped.join(", ")}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
